/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: { query?: never; header?: never; path?: never; cookie?: never };
        get?: never; put?: never;
        post: {
            parameters: { query?: never; header?: never; path?: never; cookie?: never };
            requestBody: { content: { "application/json": { email: string; password: string; display_name: string } } };
            responses: { 201: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["User"] } } };
        };
        delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/auth/login": {
        parameters: { query?: never; header?: never; path?: never; cookie?: never };
        get?: never; put?: never;
        post: {
            parameters: { query?: never; header?: never; path?: never; cookie?: never };
            requestBody: { content: { "application/json": { email: string; password: string } } };
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["User"] } } };
        };
        delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/auth/logout": {
        parameters: { query?: never; header?: never; path?: never; cookie?: never };
        get?: never; put?: never;
        post: {
            parameters: { query?: never; header?: never; path?: never; cookie?: never };
            requestBody?: never;
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": { status: string } } } };
        };
        delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/auth/me": {
        parameters: { query?: never; header?: never; path?: never; cookie?: never };
        get: {
            parameters: { query?: never; header?: never; path?: never; cookie?: never };
            requestBody?: never;
            responses: {
                200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["User"] } };
                401: { headers: { [name: string]: unknown }; content?: never };
            };
        };
        put?: never; post?: never; delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/org/subsidiaries": {
        parameters: { query?: never; header?: never; path?: never; cookie?: never };
        get: {
            parameters: { query?: never; header?: never; path?: never; cookie?: never };
            requestBody?: never;
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["Subsidiary"][] } } };
        };
        put?: never;
        post: {
            parameters: { query?: never; header?: never; path?: never; cookie?: never };
            requestBody: { content: { "application/json": { code: string; name: string } } };
            responses: { 201: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["Subsidiary"] } } };
        };
        delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/healthz": {
        parameters: { query?: never; header?: never; path?: never; cookie?: never };
        get: { parameters: { query?: never; header?: never; path?: never; cookie?: never }; requestBody?: never; responses: { 200: { headers: { [name: string]: unknown }; content?: never } } };
        put?: never; post?: never; delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/readyz": {
        parameters: { query?: never; header?: never; path?: never; cookie?: never };
        get: { parameters: { query?: never; header?: never; path?: never; cookie?: never }; requestBody?: never; responses: { 200: { headers: { [name: string]: unknown }; content?: never } } };
        put?: never; post?: never; delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/onboarding/cases": {
        parameters: { query?: never; header?: never; path?: never; cookie?: never };
        get: {
            parameters: { query: { subsidiary_id: string; state?: string }; header?: never; path?: never; cookie?: never };
            requestBody?: never;
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["OnboardingCase"][] } } };
        };
        post: {
            parameters: { query?: never; header?: never; path?: never; cookie?: never };
            requestBody: { content: { "application/json": { client_id: string } } };
            responses: { 201: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["OnboardingCase"] } } };
        };
        put?: never; delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/onboarding/cases/{id}": {
        parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
        get: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody?: never;
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["CaseDetails"] } } };
        };
        put?: never; post?: never; delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/onboarding/cases/{id}/application": {
        parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
        get?: never;
        put: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody: { content: { "application/json": components["schemas"]["ApplicationData"] } };
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["ApplicationData"] } } };
        };
        post?: never; delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/onboarding/cases/{id}/requirements": {
        parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
        get: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody?: never;
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["RequirementInstance"][] } } };
        };
        put?: never; post?: never; delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/onboarding/cases/{id}/documents": {
        parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
        get?: never; put?: never;
        post: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody: { content: { "multipart/form-data": { file: Blob; requirement_key: string } } };
            responses: { 201: { headers: { [name: string]: unknown }; content: { "application/json": { document: components["schemas"]["Document"]; requirement: components["schemas"]["RequirementInstance"] } } } };
        };
        delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/onboarding/cases/{id}/submit": {
        parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
        get?: never; put?: never;
        post: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody?: never;
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["OnboardingCase"] } } };
        };
        delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/onboarding/cases/{id}/compliance": {
        parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
        get: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody?: never;
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["ComplianceCheck"][] } } };
        };
        put?: never;
        post: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody: { content: { "application/json": { check_type: string; outcome: "pass" | "fail" | "needs_info"; notes?: string } } };
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["ComplianceCheck"] } } };
        };
        delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/onboarding/clients": {
        parameters: { query?: never; header?: never; path?: never; cookie?: never };
        get: {
            parameters: { query: { subsidiary_id: string }; header?: never; path?: never; cookie?: never };
            requestBody?: never;
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["Client"][] } } };
        };
        put?: never;
        post: {
            parameters: { query?: never; header?: never; path?: never; cookie?: never };
            requestBody: { content: { "application/json": { subsidiary_id: string; client_type?: string; display_name: string; broker_id?: string } } };
            responses: { 201: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["Client"] } } };
        };
        delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/onboarding/clients/{id}": {
        parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
        get: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody?: never;
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["Client"] } } };
        };
        put?: never; post?: never; delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/onboarding/clients/{id}/rm": {
        parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
        get?: never; put?: never;
        post: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody: { content: { "application/json": { rm_person_id: string; subsidiary_id: string } } };
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": unknown } } };
        };
        delete: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody?: never;
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": unknown } } };
        };
        options?: never; head?: never; patch?: never; trace?: never;
    };
    "/approval/queue": {
        parameters: { query?: never; header?: never; path?: never; cookie?: never };
        get: {
            parameters: { query?: never; header?: never; path?: never; cookie?: never };
            requestBody?: never;
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["ApprovalQueueItem"][] } } };
        };
        put?: never; post?: never; delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/approval/requests/{id}": {
        parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
        get: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody?: never;
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["ApprovalRequestDetails"] } } };
        };
        put?: never; post?: never; delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/reconciliation/accounts": {
        parameters: { query?: never; header?: never; path?: never; cookie?: never };
        get: {
            parameters: { query: { subsidiary_id: string }; header?: never; path?: never; cookie?: never };
            requestBody?: never;
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["BankAccount"][] } } };
        };
        put?: never;
        post: {
            parameters: { query?: never; header?: never; path?: never; cookie?: never };
            requestBody: { content: { "application/json": { subsidiary_id: string; bank_name: string; account_number: string; account_name: string; currency?: string; parser_column_map?: Record<string, string> } } };
            responses: { 201: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["BankAccount"] } } };
        };
        delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/reconciliation/accounts/{id}/statements": {
        parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
        get: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody?: never;
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["BankStatement"][] } } };
        };
        put?: never;
        post: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody: { content: { "multipart/form-data": { file: Blob; period_start: string; period_end: string; opening_balance?: string; closing_balance?: string } } };
            responses: { 201: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["BankStatement"] } } };
        };
        delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/reconciliation/transactions": {
        parameters: { query?: never; header?: never; path?: never; cookie?: never };
        get?: never; put?: never;
        post: {
            parameters: { query?: never; header?: never; path?: never; cookie?: never };
            requestBody: { content: { "application/json": { subsidiary_id: string; bank_account_id?: string; type: string; direction: string; amount_kobo: number; currency?: string; reference?: string; client_id?: string; txn_date: string } } };
            responses: { 201: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["InternalTransaction"] } } };
        };
        delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/reconciliation/runs": {
        parameters: { query?: never; header?: never; path?: never; cookie?: never };
        get: {
            parameters: { query: { bank_account_id: string }; header?: never; path?: never; cookie?: never };
            requestBody?: never;
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["ReconciliationRun"][] } } };
        };
        put?: never;
        post: {
            parameters: { query?: never; header?: never; path?: never; cookie?: never };
            requestBody: { content: { "application/json": { bank_account_id: string; period_start: string; period_end: string } } };
            responses: { 201: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["ReconciliationRun"] } } };
        };
        delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/reconciliation/runs/{id}": {
        parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
        get: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody?: never;
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["RunDetails"] } } };
        };
        put?: never; post?: never; delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/reconciliation/runs/{id}/unmatched": {
        parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
        get: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody?: never;
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["UnmatchedItems"] } } };
        };
        put?: never; post?: never; delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/reconciliation/runs/{id}/match": {
        parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
        get?: never; put?: never;
        post: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody: { content: { "application/json": { bank_line_id: string; internal_txn_id: string; notes?: string } } };
            responses: { 201: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["ReconMatch"] } } };
        };
        delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/reconciliation/runs/{id}/unmatched-bank": {
        parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
        get?: never; put?: never;
        post: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody: { content: { "application/json": { bank_line_id: string; notes?: string } } };
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["ReconMatch"] } } };
        };
        delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/reconciliation/runs/{id}/unmatched-internal": {
        parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
        get?: never; put?: never;
        post: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody: { content: { "application/json": { internal_txn_id: string; notes?: string } } };
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["ReconMatch"] } } };
        };
        delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/reconciliation/runs/{id}/close": {
        parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
        get?: never; put?: never;
        post: {
            parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
            requestBody?: never;
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["ReconciliationRun"] } } };
        };
        delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/approval/requests/{id}/steps/{stepId}/decide": {
        parameters: { query?: never; header?: never; path: { id: string; stepId: string }; cookie?: never };
        get?: never; put?: never;
        post: {
            parameters: { query?: never; header?: never; path: { id: string; stepId: string }; cookie?: never };
            requestBody: { content: { "application/json": { action: "approve" | "reject" | "return"; notes?: string } } };
            responses: { 200: { headers: { [name: string]: unknown }; content: { "application/json": { status: string } } } };
        };
        delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
}

export interface components {
    schemas: {
        User: {
            ID: string;
            Email: string;
            DisplayName: string;
            CreatedAt: string;
        };
        Subsidiary: {
            ID: string;
            Code: string;
            Name: string;
        };
        OnboardingCase: {
            ID: string;
            ClientID: string;
            SubsidiaryID: string;
            ClientType: string;
            State: string;
            RiskFlag: boolean;
            RiskNotes?: string;
            ReturnNotes?: string;
            ReturnCount?: number;
            RequirementSetVersion?: number;
            InitiatedBy?: string;
            TNCVersion?: string;
            TNCAcceptedAt?: string;
            SubmittedAt?: string;
        };
        ApplicationData: {
            case_id?: string;
            full_name?: string;
            gender?: string;
            mothers_maiden_name?: string;
            date_of_birth?: string;
            place_of_birth?: string;
            country_of_origin?: string;
            place_of_residence?: string;
            residential_address?: string;
            is_us_person?: boolean;
            us_address?: string;
            phone_numbers?: string[];
            email?: string;
            tin?: string;
            next_of_kin_name?: string;
            next_of_kin_email?: string;
            next_of_kin_phone?: string;
            employer?: string;
            employer_address?: string;
            official_email?: string;
            official_phone?: string;
            is_pep?: boolean;
            pep_position?: string;
            pep_period?: string;
            social_media?: Record<string, string>;
            source_of_funds?: string;
            source_of_wealth?: string;
            investment_purpose?: string;
            investment_amount_kobo?: number;
            investment_amount_words?: string;
            tenor?: string;
            interest_rate_bps?: number;
            bank_name?: string;
            bank_account_name?: string;
            bank_account_number?: string;
            bvn?: string;
            sort_code?: string;
            declaration_legal_capacity?: boolean;
            declaration_info_correct?: boolean;
            declaration_tnc_accepted?: boolean;
            declaration_min_holding?: boolean;
        };
        RequirementInstance: {
            ID?: string;
            id?: string;
            CaseID?: string;
            case_id?: string;
            RequirementKey?: string;
            requirement_key?: string;
            Label?: string;
            label?: string;
            Category?: string;
            category?: string;
            Obligation?: string;
            obligation?: string;
            Status?: string;
            status?: string;
            DocumentID?: string;
            document_id?: string;
            SatisfiedAt?: string;
            satisfied_at?: string;
        };
        CaseDetails: {
            case?: components["schemas"]["OnboardingCase"];
            application?: components["schemas"]["ApplicationData"];
            requirements?: components["schemas"]["RequirementInstance"][];
            can_submit?: boolean;
        };
        Client: {
            ID: string;
            SubsidiaryID: string;
            ClientType: string;
            DisplayName: string;
            Status: string;
            BrokerID?: string;
        };
        Document: {
            ID: string;
            Filename: string;
            Mime: string;
            Size: number;
            ScanStatus: string;
            CreatedAt: string;
        };
        ComplianceCheck: {
            ID: string;
            CaseID: string;
            CheckType: string;
            Outcome: string;
            Notes: string;
            Source: string;
            PerformedBy: string;
            PerformedAt: string;
        };
        ApprovalStep: {
            ID: string;
            RequestID: string;
            StepOrder: number;
            PositionID: string;
            Label: string;
            Status: string;
            DecidedBy?: string;
            Notes?: string;
        };
        ApprovalRequest: {
            ID: string;
            ResourceType: string;
            ResourceID: string;
            RoutingKey: string;
            Status: string;
            CreatedBy: string;
        };
        ApprovalRequestDetails: {
            request: components["schemas"]["ApprovalRequest"];
            steps: components["schemas"]["ApprovalStep"][];
        };
        BankAccount: {
            id: string;
            subsidiary_id: string;
            bank_name: string;
            account_number: string;
            account_name: string;
            currency: string;
            parser_column_map?: Record<string, string>;
            status: string;
        };
        BankStatement: {
            id: string;
            bank_account_id: string;
            period_start: string;
            period_end: string;
            opening_balance: number;
            closing_balance: number;
            status: string;
            imported_by: string;
        };
        StatementLine: {
            id: string;
            statement_id: string;
            txn_date: string;
            value_date?: string;
            debit_kobo: number;
            credit_kobo: number;
            balance_kobo?: number;
            narration: string;
            reference: string;
        };
        InternalTransaction: {
            id: string;
            subsidiary_id: string;
            bank_account_id?: string;
            type: string;
            direction: string;
            amount_kobo: number;
            currency: string;
            reference: string;
            client_id?: string;
            txn_date: string;
        };
        ReconciliationRun: {
            id: string;
            bank_account_id: string;
            period_start: string;
            period_end: string;
            status: string;
            reconciled_by?: string;
        };
        ReconMatch: {
            id: string;
            run_id: string;
            bank_line_id?: string;
            internal_txn_id?: string;
            status: string;
            match_type: string;
            confidence_pct?: number;
            notes: string;
        };
        RunSummary: {
            matched: number;
            unmatched_bank: number;
            unmatched_internal: number;
            total_bank_lines: number;
            total_internal_txns: number;
        };
        RunDetails: {
            run: components["schemas"]["ReconciliationRun"];
            summary: components["schemas"]["RunSummary"];
            matches: components["schemas"]["ReconMatch"][];
        };
        UnmatchedItems: {
            bank_lines: components["schemas"]["StatementLine"][];
            internal_txns: components["schemas"]["InternalTransaction"][];
        };
        ApprovalQueueItem: {
            step: components["schemas"]["ApprovalStep"];
            resource_type: string;
            resource_id: string;
            context?: Record<string, unknown>;
        };
    };
}
