"use strict";
// ---------- Balanced Scorecard library (13 departments) ----------
const PORDER = ["Financial", "Client / Customer", "Internal Business Process", "Learning & Growth"];
const DEPTS = {
  "Human Capital Management": { "Financial": [["Manage HR & people-cost budget", "HR opex within budget", 8], ["Recruitment & training cost efficiency", "Cost-per-hire vs benchmark", 7]], "Client / Customer": [["Employee engagement & satisfaction", "Engagement / eNPS", 9], ["HR service delivery", "Internal satisfaction; SLA", 8], ["Time-to-fill vacancies", "Time-to-fill vs target", 8]], "Internal Business Process": [["Payroll accuracy & timeliness", "% accurate & on time", 10], ["HR & regulatory compliance", "Findings; policy adherence", 9], ["HRIS data quality", "Record accuracy", 8], ["Onboarding cycle time", "Onboarding turnaround", 8]], "Learning & Growth": [["Workforce capability", "Training completion %", 7], ["Talent & succession", "Succession coverage", 6], ["Compliance training", "% completed", 6], ["Personal development", "Goals achieved", 6]] },
  "Wealth Management": { "Financial": [["Revenue / fee income", "Fee income vs target", 13], ["AUM growth", "AUM growth % vs target", 12], ["Net new money", "Net new assets", 10]], "Client / Customer": [["Client retention", "Retention rate %", 10], ["Client acquisition", "New qualified clients", 10], ["Client satisfaction & suitability", "NPS; suitability reviews", 10]], "Internal Business Process": [["KYC / suitability compliance", "% compliant; zero breaches", 10], ["Advisory documentation & turnaround", "Accuracy; turnaround", 10]], "Learning & Growth": [["Professional certification", "Certifications maintained", 8], ["Product knowledge & development", "CPD; training", 7]] },
  "Portfolio Management": { "Financial": [["Portfolio performance vs benchmark", "Return vs benchmark", 14], ["Risk-adjusted return", "Sharpe vs target", 11], ["AUM & fee revenue", "AUM; fee revenue", 10]], "Client / Customer": [["Mandate objective achievement", "% mandates met", 9], ["Client satisfaction", "Satisfaction score", 8], ["Reporting quality & timeliness", "On-time, accurate", 8]], "Internal Business Process": [["Investment-guideline compliance", "Breaches (target zero)", 10], ["Risk-limit adherence", "% within limits", 8], ["Trade & reconciliation accuracy", "Break rate", 7]], "Learning & Growth": [["Research & analytical capability", "Research; CPD", 8], ["Professional certification (CFA)", "Progress / maintenance", 7]] },
  "Market Research and Trading Support": { "Financial": [["Cost efficiency of research", "Within budget", 5], ["Revenue from research ideas", "Idea performance", 5]], "Client / Customer": [["Research quality & relevance", "Desk quality rating", 10], ["Timeliness of research & support", "On time", 10], ["Coverage & responsiveness", "Coverage; response time", 10]], "Internal Business Process": [["Accuracy of analysis & data", "Error rate (low)", 12], ["Model & data integrity", "Models validated", 10], ["Trade-support SLA", "% within SLA", 10], ["Report turnaround", "Turnaround vs target", 8]], "Learning & Growth": [["Analytical & technical skills", "Skills; tools", 7], ["Certification & market knowledge", "CPD", 7], ["Personal development", "Goals achieved", 6]] },
  "Trading": { "Financial": [["Trading P&L vs target", "Net P&L vs target", 18], ["Trading revenue contribution", "Revenue vs target", 12], ["Execution cost / slippage", "Slippage vs benchmark", 10]], "Client / Customer": [["Best execution & desk service", "Adherence; satisfaction", 12], ["Responsiveness & fill quality", "Fill quality; response", 8]], "Internal Business Process": [["Risk & position-limit adherence", "Breaches (target zero)", 10], ["Trade error & cancel rate", "Error rate (low)", 8], ["Regulatory & conduct compliance", "Compliance; recon", 7]], "Learning & Growth": [["Market & product knowledge", "Depth; CPD", 8], ["Systems proficiency", "Tools; development", 7]] },
  "Risk Management": { "Financial": [["Cost of risk & efficiency", "Within budget", 8], ["Losses within risk appetite", "Losses vs appetite", 7]], "Client / Customer": [["Risk reporting quality & timeliness", "Timely, accurate", 7], ["Advisory & support to business", "Stakeholder satisfaction", 7], ["Regulator & audit relationship", "Findings resolved", 6]], "Internal Business Process": [["Risk identification & assessment", "% risks assessed", 12], ["Control effectiveness & monitoring", "Test pass rate", 11], ["Limit monitoring & breach resolution", "Resolved on time", 11], ["Regulatory compliance & model validation", "Compliance; validated", 11]], "Learning & Growth": [["Risk methodology capability", "Capability; CPD", 7], ["Certification (FRM / PRM)", "Progress", 7], ["Personal development", "Goals achieved", 6]] },
  "Finance and Operations": { "Financial": [["Cost / budget management", "Opex vs budget", 9], ["Financial reporting accuracy", "Error-free reporting", 9], ["Working-capital / cash management", "Targets met", 7]], "Client / Customer": [["Service to business units", "Internal satisfaction", 7], ["Query / request resolution", "% within SLA", 7], ["Reporting timeliness", "On time", 6]], "Internal Business Process": [["Month-end close cycle time", "Within target days", 10], ["Reconciliation & settlement accuracy", "Break rate", 10], ["Controls & regulatory compliance", "Compliance; findings", 10], ["Straight-through processing", "STP rate", 10]], "Learning & Growth": [["Certification (ICAN / ACCA)", "Progress", 6], ["Systems & process capability", "Proficiency; improvements", 5], ["Personal development", "Goals achieved", 4]] },
  "Legal & Admin": { "Financial": [["Manage legal & admin budget", "Within budget", 8], ["Cost-efficient counsel & procurement", "Spend vs benchmark", 7]], "Client / Customer": [["Legal / admin advisory service", "Satisfaction; turnaround", 9], ["Contract / request turnaround", "Turnaround vs SLA", 8], ["Facilities & admin service quality", "Internal satisfaction", 8]], "Internal Business Process": [["Contract drafting & management", "Accurate & on time", 11], ["Legal & regulatory compliance", "No material lapses", 11], ["Litigation & dispute management", "Exposure contained", 9], ["Records & facilities administration", "Accuracy; effective", 9]], "Learning & Growth": [["Capability & knowledge currency", "Knowledge; CPD", 7], ["Certification / licence", "Maintained", 7], ["Personal development", "Goals achieved", 6]] },
  "Internal Control": { "Financial": [["Cost efficiency of function", "Within budget", 5], ["Control losses prevented", "Reduction in losses", 5]], "Client / Customer": [["Assurance reporting quality", "Timely, accurate", 7], ["Advisory & support on controls", "Stakeholder satisfaction", 7], ["Audit committee / regulator relationship", "No lapses", 6]], "Internal Business Process": [["Control testing & assurance coverage", "% reviews completed", 13], ["Control effectiveness & exceptions", "Test pass rate", 13], ["Issue / remediation closure", "% on time", 12], ["Compliance monitoring", "Breaches; adherence", 12]], "Learning & Growth": [["Controls & audit methodology", "Capability; CPD", 7], ["Certification (CIA / ACA)", "Progress", 7], ["Personal development", "Goals achieved", 6]] },
  "Business Development": { "Financial": [["Revenue / deal origination vs target", "Originated revenue vs target", 14], ["New mandates / AUM won", "Mandates / net new AUM", 12], ["Cost of acquisition efficiency", "Cost vs benchmark", 6]], "Client / Customer": [["New client / partner acquisition", "Qualified new clients/partners", 12], ["Client & partner satisfaction / retention", "Satisfaction; retention", 10], ["Pipeline coverage", "Pipeline vs target", 8]], "Internal Business Process": [["Deal / proposal quality & turnaround", "Quality; turnaround", 10], ["CRM / pipeline data quality & compliance", "Data quality; KYC", 8]], "Learning & Growth": [["Market & product knowledge", "Knowledge; CPD", 7], ["Certification & development", "Maintained", 6], ["Personal development", "Goals achieved", 7]] },
  "Technology / IT": { "Financial": [["IT cost / budget efficiency", "Within budget", 8], ["Value delivered vs plan", "Deliverables vs roadmap", 7]], "Client / Customer": [["Internal user satisfaction / support SLA", "Satisfaction; SLA", 12], ["System availability / uptime", "Uptime vs target", 10], ["Responsiveness", "Response / resolution time", 8]], "Internal Business Process": [["Delivery quality & timeliness", "On-time, quality", 12], ["Security & access controls", "Controls; incidents", 10], ["Incident / bug resolution", "Resolution rate/time", 10], ["Documentation", "Completeness", 5]], "Learning & Growth": [["Technical skills & certification", "Skills; certifications", 10], ["Personal development", "Goals achieved", 8]] },
  "Brand & Strategy": { "Financial": [["Marketing spend efficiency / ROI", "Spend ROI vs target", 10], ["Contribution to growth initiatives", "Impact on revenue/growth", 8]], "Client / Customer": [["Brand awareness & perception", "Awareness / perception", 12], ["Stakeholder / campaign satisfaction", "Satisfaction", 10], ["Reach & engagement", "Reach / engagement", 8]], "Internal Business Process": [["Campaign & project delivery", "On-time, quality", 12], ["Brand consistency & compliance", "Consistency; approvals", 10], ["Content / asset turnaround", "Turnaround vs SLA", 8]], "Learning & Growth": [["Market & competitor insight", "Insight; CPD", 8], ["Tools & capability", "Proficiency", 8], ["Personal development", "Goals achieved", 6]] },
  "Executive / Leadership": { "Financial": [["Entity financial performance vs plan", "Revenue / PBT vs plan", 16], ["Cost & capital efficiency", "Cost / capital ratios", 10]], "Client / Customer": [["Market position & key stakeholders", "Market share; outcomes", 12], ["Regulator & board confidence", "Findings; confidence", 8]], "Internal Business Process": [["Governance, risk & compliance posture", "Compliance; risk posture", 14], ["Operational excellence & delivery", "Delivery vs plan", 10]], "Learning & Growth": [["Talent & succession", "Succession coverage", 12], ["Culture & engagement", "Engagement score", 8], ["Strategic leadership & development", "Strategy execution", 10]] },
};

const CO_NAME = { PCL: "Page Capital Limited", PAML: "Page Asset Management Limited", "SHARED SERVICE": "Shared Services", GROUP: "Shared Services" };
const CO_DOMAIN = { PCL: "pagecapital.com", PAML: "pageassetmgt.com", "SHARED SERVICE": "pagegroup.com", GROUP: "pagegroup.com" };
const GRADE_TIER = { "Intern": 1, "Analyst//Executive Trainee": 1, "Associate//Executive Trainee": 1, "Analyst": 1, "Associate": 2, "Executive Associate": 2, "Senior Executive Associate": 2, "Assistant Manager": 3, "Deputy Manager": 3, "F & G Consultant": 3, "Manager": 4, "Senior Manager": 4, "F&G Executive Consultant": 4, "Assistant Vice President": 5, "Assistant Vice President//Vice President I": 5, "Vice President": 5, "Senior Vice President": 5, "Senior Executive Consultant": 5, "Group Executive": 6 };
const LVL = ["", "IC · L1", "Manager · L2", "Head/Exec · L3"];

function deptOf(role) {
  const r = String(role || "").toLowerCase();
  if (r.includes("wealth")) return "Wealth Management";
  if (r.includes("portfolio") || r.includes("investment")) return "Portfolio Management";
  if (r.includes("trading support") || r.includes("research") || r.includes("quantitative")) return "Market Research and Trading Support";
  if (r.includes("trader")) return "Trading";
  if (r.includes("risk")) return "Risk Management";
  if (r.includes("internal control") || r.includes("compliance")) return "Internal Control";
  if (r.includes("human resources") || /\bhr\b/.test(r)) return "Human Capital Management";
  if (r.includes("finance") || r.includes("operations") || r.includes("treasury") || r.includes("fund") || r.includes("financial") || r.includes("controller")) return "Finance and Operations";
  if (r.includes("admin") || r.includes("logistics")) return "Legal & Admin";
  if (r.includes("business development")) return "Business Development";
  if (r.includes("brand") || r.includes("strategy")) return "Brand & Strategy";
  if (r.includes("software") || r.includes("it support") || r.includes("data analyst")) return "Technology / IT";
  if (r.includes("managing director")) return "Executive / Leadership";
  return "Finance and Operations";
}
function scopeOf(role) {
  const r = String(role || "").toLowerCase();
  if (r.includes("group head") || r.includes("head of") || r.includes("head,") || r.startsWith("head") || r.includes("managing director") || r.includes("chief")) return "Head";
  if (r.includes("team lead") || r.startsWith("lead") || r.includes("lead ")) return "Lead";
  return "IC";
}
function levelOf(grade, role, isManager) {
  const tier = GRADE_TIER[grade] || 3, scope = scopeOf(role);
  return Math.max(scope === "Head" ? 3 : scope === "Lead" ? 2 : 1, tier >= 5 ? 3 : tier >= 4 ? 2 : 1, isManager ? 2 : 1);
}

// ---------- scoring (operates on a KPI list supplied by scorecards.js) ----------
const kid = (p, i) => `${p}#${i}`;
function overall(kpiList, ratings) { let s = 0, any = false; (kpiList || []).forEach((k) => { const r = ratings && ratings[k.id]; if (r) { s += (k.w / 100) * r; any = true; } }); return any ? Math.round(s * 100) / 100 : 0; }
function band(s) { if (!s) return "—"; if (s >= 4.5) return "Outstanding"; if (s >= 3.5) return "Exceeds Expectations"; if (s >= 2.5) return "Meets Expectations"; if (s >= 1.5) return "Needs Improvement"; return "Unsatisfactory"; }
function allRated(kpiList, ratings) { return (kpiList || []).length > 0 && kpiList.every((k) => ratings && ratings[k.id]); }

module.exports = { PORDER, DEPTS, CO_NAME, CO_DOMAIN, GRADE_TIER, LVL, deptOf, scopeOf, levelOf, kid, overall, band, allRated };
